name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: cargo fmt --check

      - uses: volta-cli/action@v4

      - run: npm ci
      - run: npm run build

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ./target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
      - run: cargo test
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
